export const TEXTS = {
  app: {
    name: 'مصروفي',
    subtitle: 'مدير المصاريف الشخصية',
  },
  navigation: {
    home: 'الرئيسية',
    stats: 'الإحصائيات',
    settings: 'الإعدادات',
  },
  home: {
    balance: 'الرصيد الحالي',
    monthlyIncome: 'الدخل الشهري',
    monthlyExpense: 'المصاريف الشهرية',
    recentTransactions: 'المعاملات الأخيرة',
    addTransaction: 'إضافة معاملة',
    noTransactions: 'لا توجد معاملات',
  },
  transaction: {
    income: 'دخل',
    expense: 'مصروف',
    amount: 'المبلغ',
    category: 'الفئة',
    date: 'التاريخ',
    note: 'ملاحظة',
    save: 'حفظ',
    cancel: 'إلغاء',
    delete: 'حذف',
  },
  stats: {
    title: 'الإحصائيات',
    monthlyOverview: 'نظرة عامة شهرية',
    categoryBreakdown: 'تفصيل حسب الفئة',
    selectMonth: 'اختر الشهر',
  },
  settings: {
    title: 'الإعدادات',
    appearance: 'المظهر',
    darkMode: 'الوضع المظلم',
    security: 'الأمان',
    enableSecurity: 'تفعيل الحماية',
    securityType: 'نوع الحماية',
    pin: 'رمز PIN',
    biometric: 'بصمة الإصبع',
    data: 'البيانات',
    clearData: 'مسح جميع البيانات',
    exportData: 'تصدير البيانات',
    currency: 'العملة',
    language: 'اللغة',
    notifications: 'الإشعارات',
    dailyReminder: 'تذكير يومي',
    exportData: 'تصدير البيانات',
    currency: 'العملة',
    language: 'اللغة',
    notifications: 'الإشعارات',
    dailyReminder: 'تذكير يومي',
    about: 'حول التطبيق',
  },
  security: {
    enterPin: 'أدخل رمز PIN',
    setPin: 'تعيين رمز PIN',
    confirmPin: 'تأكيد رمز PIN',
    useBiometric: 'استخدم بصمة الإصبع',
    wrongPin: 'رمز PIN خاطئ',
    pinMismatch: 'الرموز غير متطابقة',
    tooManyAttempts: 'محاولات كثيرة خاطئة. حاول مرة أخرى خلال {seconds} ثانية',
    switchToPin: 'التبديل إلى رمز PIN',
    switchToBiometric: 'التبديل إلى بصمة الإصبع',
    tooManyAttempts: 'محاولات كثيرة خاطئة. حاول مرة أخرى خلال {seconds} ثانية',
    attemptsRemaining: 'المحاولات المتبقية: {attempts}',
  },
  validation: {
    amountRequired: 'المبلغ مطلوب',
    amountMustBePositive: 'المبلغ يجب أن يكون أكبر من صفر',
    categoryRequired: 'الفئة مطلوبة',
    invalidAmount: 'مبلغ غير صحيح',
  },
  export: {
    success: 'تم تصدير البيانات بنجاح',
    error: 'خطأ في تصدير البيانات',
    noData: 'لا توجد بيانات للتصدير',
  },
  validation: {
    amountRequired: 'المبلغ مطلوب',
    amountMustBePositive: 'المبلغ يجب أن يكون أكبر من صفر',
    categoryRequired: 'الفئة مطلوبة',
    invalidAmount: 'مبلغ غير صحيح',
  },
  export: {
    success: 'تم تصدير البيانات بنجاح',
    error: 'خطأ في تصدير البيانات',
    noData: 'لا توجد بيانات للتصدير',
  },
  common: {
    ok: 'موافق',
    cancel: 'إلغاء',
    delete: 'حذف',
    edit: 'تعديل',
    save: 'حفظ',
    confirm: 'تأكيد',
    retry: 'إعادة المحاولة',
    export: 'تصدير',
    confirm: 'تأكيد',
    retry: 'إعادة المحاولة',
    loading: 'جاري التحميل...',
    error: 'خطأ',
    success: 'تم بنجاح',
    da: 'د.ج',
    location: 'الموقع',
    optional: 'اختياري',
    location: 'الموقع',
  },
};